spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_judge?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
mybatis:
  config-location: classpath:mybatis-config.xml

judger:
  path: http://127.0.0.1:8080